name: CI

on:
  push:
    branches: [master, next]
  pull_request:
    branches: [master, next]

env:
  NODE_VERSION: "16"

jobs:
  lint:
    name: Check linting problems
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Update NPM to v7
        run: npm install -g npm@7
      
      - name: Install eslint tooling
        run: npm ci

      - name: Run linter
        run: npm run lint

  unit-testing:
    name: Run unit testing
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Update NPM to v7
        run: npm install -g npm@7

      - name: Install global dependencies
        run: npm install -g pm2

      - name: Install local dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Update coverage report
        uses: coverallsapp/github-action@master
        if: matrix.node-version == '16.x'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}